-- ============================================================================
-- RUBSAL POS — V1 foundation schema
-- Businesses (tenants), stores, RBAC (roles/permissions), employees, tokens.
-- ============================================================================

CREATE TABLE businesses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    owner_name    VARCHAR(255),
    owner_phone   VARCHAR(50),
    logo_url      VARCHAR(1024),
    currency      VARCHAR(3)   NOT NULL DEFAULT 'EUR',
    locale        VARCHAR(20)  NOT NULL DEFAULT 'en-US',
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE stores (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT      NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    is_main     BOOLEAN     NOT NULL DEFAULT FALSE,
    address     VARCHAR(512),
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_stores_business ON stores (business_id);

CREATE TABLE permissions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id    BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    permission_key VARCHAR(150) NOT NULL,
    description    VARCHAR(512),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_permission_business_key UNIQUE (business_id, permission_key)
);
CREATE INDEX idx_permissions_business ON permissions (business_id);

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(512),
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_role_business_name UNIQUE (business_id, name)
);
CREATE INDEX idx_roles_business ON roles (business_id);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE employees (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    full_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    pin_hash      VARCHAR(255),
    store_id      BIGINT REFERENCES stores (id) ON DELETE SET NULL,
    role_id       BIGINT REFERENCES roles (id) ON DELETE SET NULL,
    avatar_url    VARCHAR(1024),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    sales_total   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tips_total    NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_employee_business_email UNIQUE (business_id, email)
);
CREATE INDEX idx_employees_business ON employees (business_id);
CREATE INDEX idx_employees_store ON employees (store_id);

CREATE TABLE refresh_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash     VARCHAR(255) NOT NULL UNIQUE,
    principal_type VARCHAR(20)  NOT NULL,
    principal_id   BIGINT       NOT NULL,
    business_id    BIGINT,
    expires_at     TIMESTAMPTZ  NOT NULL,
    revoked        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_refresh_tokens_principal ON refresh_tokens (principal_type, principal_id);
