-- ============================================================================
-- V2 — Catalog: categories, products, and product modifiers
-- ============================================================================

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    image_url   VARCHAR(1024),
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_category_business_name UNIQUE (business_id, name)
);
CREATE INDEX idx_categories_business ON categories (business_id);

CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id     BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    sku             VARCHAR(150) NOT NULL,
    barcode         VARCHAR(150),
    description     VARCHAR(2000),
    image_url       VARCHAR(1024),
    category_id     BIGINT REFERENCES categories (id) ON DELETE SET NULL,
    price           NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax_amount      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_title  VARCHAR(255),
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    available_qty   INTEGER      NOT NULL DEFAULT 0,
    quantity_sold   INTEGER      NOT NULL DEFAULT 0,
    total_qty       INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_product_business_sku UNIQUE (business_id, sku)
);
CREATE INDEX idx_products_business ON products (business_id);
CREATE INDEX idx_products_category ON products (category_id);

CREATE TABLE modifier_groups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    name       VARCHAR(255) NOT NULL,
    required   BOOLEAN      NOT NULL DEFAULT FALSE,
    min_select INTEGER      NOT NULL DEFAULT 0,
    max_select INTEGER      NOT NULL DEFAULT 1,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_modifier_groups_product ON modifier_groups (product_id);

CREATE TABLE modifier_options (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT       NOT NULL REFERENCES modifier_groups (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    price_delta NUMERIC(12, 2) NOT NULL DEFAULT 0,
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_modifier_options_group ON modifier_options (group_id);
