-- ============================================================================
-- V3 — Floor plan: floors and tables
-- ============================================================================

CREATE TABLE floors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_floor_business_name UNIQUE (business_id, name)
);
CREATE INDEX idx_floors_business ON floors (business_id);

CREATE TABLE restaurant_tables (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    name        VARCHAR(150) NOT NULL,
    floor_id    BIGINT REFERENCES floors (id) ON DELETE CASCADE,
    seats       INTEGER      NOT NULL DEFAULT 0,
    status      VARCHAR(20)  NOT NULL DEFAULT 'FREE',
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_tables_business ON restaurant_tables (business_id);
CREATE INDEX idx_tables_floor ON restaurant_tables (floor_id);
