-- ============================================================================
-- V6 — Services: a business-sold service (e.g. "Battery Replacement") that may
-- consume one or more products. Both the service line and its product lines
-- land on the final POS receipt (cashier portal, built later).
-- ============================================================================

CREATE TABLE services (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    price       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_services_business ON services (business_id);

CREATE TABLE service_products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT  NOT NULL REFERENCES services (id) ON DELETE CASCADE,
    product_id BIGINT  NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    quantity   INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_service_products_service ON service_products (service_id);
CREATE INDEX idx_service_products_product ON service_products (product_id);

-- ----------------------------------------------------------------------------
-- Back-fill the service.* permission catalog for every EXISTING business.
-- (New businesses get these from DefaultPermissions at provisioning time.)
-- Business owners derive authorities from all of their business's permissions,
-- so this alone lets existing owners use the new endpoints.
-- ----------------------------------------------------------------------------
INSERT INTO permissions (business_id, permission_key, description, created_at, updated_at)
SELECT b.id, k.pkey, k.descr, now(), now()
FROM businesses b
CROSS JOIN (VALUES
    ('service.view',   'View services'),
    ('service.create', 'Create service'),
    ('service.edit',   'Edit service'),
    ('service.delete', 'Delete service')
) AS k(pkey, descr)
ON CONFLICT (business_id, permission_key) DO NOTHING;

-- Grant all service.* perms to roles that already manage the catalog
-- (i.e. hold product.create — Manager and equivalents).
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions pc  ON pc.business_id = r.business_id AND pc.permission_key = 'product.create'
JOIN role_permissions rpc ON rpc.role_id = r.id AND rpc.permission_id = pc.id
JOIN permissions p   ON p.business_id = r.business_id
                    AND p.permission_key IN ('service.view', 'service.create', 'service.edit', 'service.delete')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Grant service.view to roles that can view the catalog (e.g. Cashier).
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions pc  ON pc.business_id = r.business_id AND pc.permission_key = 'product.view'
JOIN role_permissions rpc ON rpc.role_id = r.id AND rpc.permission_id = pc.id
JOIN permissions p   ON p.business_id = r.business_id AND p.permission_key = 'service.view'
ON CONFLICT (role_id, permission_id) DO NOTHING;
