-- ============================================================================
-- V7 — Cashier order domain: payment devices, orders, order items (+ modifier
-- snapshots) and payments. Money = NUMERIC(12,2); timestamps = timestamptz.
-- ============================================================================

-- Card terminals selectable at Card payment (per business, optionally per store).
CREATE TABLE payment_devices (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    store_id      BIGINT REFERENCES stores (id) ON DELETE SET NULL,
    serial_number VARCHAR(150) NOT NULL,
    label         VARCHAR(255),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_device_business_serial UNIQUE (business_id, serial_number)
);
CREATE INDEX idx_payment_devices_business ON payment_devices (business_id);

CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id      BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    store_id         BIGINT REFERENCES stores (id) ON DELETE SET NULL,
    order_number     BIGINT       NOT NULL,
    type             VARCHAR(20)  NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'CONFIRMED',
    table_id         BIGINT REFERENCES restaurant_tables (id) ON DELETE SET NULL,
    table_name       VARCHAR(150),
    guest_count      INTEGER      NOT NULL DEFAULT 1,
    customer_name    VARCHAR(255),
    customer_phone   VARCHAR(50),
    customer_address VARCHAR(512),
    handler_name     VARCHAR(255),
    kitchen_note     VARCHAR(1000),
    discount_type    VARCHAR(20),
    discount_value   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal         NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax_total        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_total   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total            NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_order_business_number UNIQUE (business_id, order_number)
);
CREATE INDEX idx_orders_business ON orders (business_id);
CREATE INDEX idx_orders_status ON orders (business_id, status);

CREATE TABLE order_items (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id             BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id           BIGINT REFERENCES products (id) ON DELETE SET NULL,
    product_name         VARCHAR(255) NOT NULL,
    seat_number          INTEGER,
    quantity             INTEGER      NOT NULL DEFAULT 1,
    unit_price           NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax_amount           NUMERIC(12, 2) NOT NULL DEFAULT 0,
    special_instructions VARCHAR(1000),
    line_total           NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sort_order           INTEGER      NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_order_items_order ON order_items (order_id);

-- Immutable snapshot of a selected modifier option (historical invoices never change).
CREATE TABLE order_item_modifiers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT       NOT NULL REFERENCES order_items (id) ON DELETE CASCADE,
    group_name    VARCHAR(255),
    name          VARCHAR(255) NOT NULL,
    price_delta   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_order_item_modifiers_item ON order_item_modifiers (order_item_id);

CREATE TABLE payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    method        VARCHAR(20)  NOT NULL,
    device_id     BIGINT REFERENCES payment_devices (id) ON DELETE SET NULL,
    device_serial VARCHAR(150),
    amount        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    status        VARCHAR(20)  NOT NULL DEFAULT 'SUCCESSFUL',
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_payments_order ON payments (order_id);

-- Seed one demo card terminal per existing business (new businesses get one at
-- provisioning time).
INSERT INTO payment_devices (business_id, store_id, serial_number, label, status, created_at, updated_at)
SELECT b.id,
       (SELECT s.id FROM stores s WHERE s.business_id = b.id ORDER BY s.created_at ASC LIMIT 1),
       '0821595192', 'Main Terminal', 'ACTIVE', now(), now()
FROM businesses b
ON CONFLICT (business_id, serial_number) DO NOTHING;
