-- ============================================================================
-- V9 — Labels: custom fields a business defines once (INPUT / SINGLE_SELECT /
-- MULTI_SELECT) and attaches to products and services. Attached values are
-- snapshotted (label_name, label_type) so historical display stays stable even
-- if the label definition is later renamed or deleted.
-- ============================================================================

CREATE TABLE labels (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT       NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(20)  NOT NULL,
    required    BOOLEAN      NOT NULL DEFAULT FALSE,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_labels_business_name UNIQUE (business_id, name)
);
CREATE INDEX idx_labels_business ON labels (business_id);

CREATE TABLE label_options (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_id   BIGINT       NOT NULL REFERENCES labels (id) ON DELETE CASCADE,
    value      VARCHAR(255) NOT NULL,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_label_options_label ON label_options (label_id);

-- ---- labels attached to a product ----
CREATE TABLE product_labels (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    label_id   BIGINT,  -- reference to the source definition (NULL if deleted)
    label_name VARCHAR(255) NOT NULL,
    label_type VARCHAR(20)  NOT NULL,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_product_labels_product ON product_labels (product_id);

CREATE TABLE product_label_values (
    product_label_id BIGINT       NOT NULL REFERENCES product_labels (id) ON DELETE CASCADE,
    value            VARCHAR(1000),
    sort_order       INTEGER      NOT NULL,
    PRIMARY KEY (product_label_id, sort_order)
);

-- ---- labels attached to a service ----
CREATE TABLE service_labels (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT       NOT NULL REFERENCES services (id) ON DELETE CASCADE,
    label_id   BIGINT,
    label_name VARCHAR(255) NOT NULL,
    label_type VARCHAR(20)  NOT NULL,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_service_labels_service ON service_labels (service_id);

CREATE TABLE service_label_values (
    service_label_id BIGINT       NOT NULL REFERENCES service_labels (id) ON DELETE CASCADE,
    value            VARCHAR(1000),
    sort_order       INTEGER      NOT NULL,
    PRIMARY KEY (service_label_id, sort_order)
);

-- ----------------------------------------------------------------------------
-- Back-fill the label.* permission catalog for every EXISTING business.
-- (New businesses get these from DefaultPermissions at provisioning time.)
-- ----------------------------------------------------------------------------
INSERT INTO permissions (business_id, permission_key, description, created_at, updated_at)
SELECT b.id, k.pkey, k.descr, now(), now()
FROM businesses b
CROSS JOIN (VALUES
    ('label.view',   'View labels'),
    ('label.create', 'Create label'),
    ('label.edit',   'Edit label'),
    ('label.delete', 'Delete label')
) AS k(pkey, descr)
ON CONFLICT (business_id, permission_key) DO NOTHING;

-- Grant all label.* perms to roles that already manage the catalog
-- (i.e. hold product.create — Manager and equivalents).
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions pc  ON pc.business_id = r.business_id AND pc.permission_key = 'product.create'
JOIN role_permissions rpc ON rpc.role_id = r.id AND rpc.permission_id = pc.id
JOIN permissions p   ON p.business_id = r.business_id
                    AND p.permission_key IN ('label.view', 'label.create', 'label.edit', 'label.delete')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Grant label.view to roles that can view the catalog (e.g. Cashier).
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions pc  ON pc.business_id = r.business_id AND pc.permission_key = 'product.view'
JOIN role_permissions rpc ON rpc.role_id = r.id AND rpc.permission_id = pc.id
JOIN permissions p   ON p.business_id = r.business_id AND p.permission_key = 'label.view'
ON CONFLICT (role_id, permission_id) DO NOTHING;
